const Privileges = {
	REMOVE_USER: 1,
	GET_ALL_USERS: 2,
	ADD_HOSPITAL: 3,
	REMOVE_HOSPITAL: 4,
	GET_ALL_HOSPITALS: 5,
	GET_ALL_PRIVILEGES: 6,
	ADD_PRIVILEGE: 7,
	ADD_ROLE: 8,
	GET_ALL_ROLES: 9,
	GET_ALL_TERMINS: 10,
	ADD_TERMIN: 11,
	REMOVE_TERMIN: 12,
	ADD_ROLEPRIVILEGE: 13,
	GET_ROLEPRIVILEGES: 14,
	REMOVE_ROLEPRIVILEGE: 15,
	ADD_USERHOSPITAL: 16,
	GET_USERHOSPITALS: 17,
	REMOVE_USERHOSPITAL: 18,
	ADD_USERROLE: 19,
	REMOVE_USERROLE: 20,
	GET_ALL_USERROLES: 21
};

module.exports = Privileges;
